### ISSUE TITLE
Proposal: Unify kafl entrypoints

### ISSUE THREAD

**Issue by Wenzel** [IntelLabs/kafl.fuzzer#13]
# Issue

The kAFL fuzzer consists of multiple scripts/entrypoints today:
~~~Python3
      scripts = ['kafl_fuzz.py', 'kafl_debug.py',
          'kafl_cov.py', 'kafl_plot.py',
          'kafl_gui.py', 'scripts/mcat.py'],
~~~

As we are working in parallel on the Dockerization of kafl, only a single entrypoint can be specified in a Docker image:
https://github.com/Wenzel/kAFL/blob/docker/Dockerfile#L29
~~~Dockerfile
...
ENTRYPOINT ["kafl_fuzz.py"]
~~~

I propose to unify these scripts into a single kafl entrypoint.

# Benefits

- single `kafl` entrypoint
- subcommands syntax, just like `git`
- exploring the command line possibilities becomes more intuitive

# Proposal

Leverage Python's [`__main__.py`](https://docs.python.org/3/library/__main__.html#main-py-in-python-packages) feature to make `kafl_fuzzer`'s package executable, and move
- `kafl_fuzz.py`
- `kafl_debug.py`
- `kafl_cov.py`
- `kafl_plot.py`
- `kafl_gui.py`

there.

Since `kafl_cov.py`, `kafl_plot.py` and `kafl_plot.py` contains a lot of code, refactoring will be necessary to split them into modules/packages if necessary.

**Comment by il-steffen** [comment]
Yes please, but if we change the cmdline like this I think we should also use the chance to refactor `kafl_debug.py`.

This tool implements helper and debug functions but they are mostly redundant and not well maintained. The actions (`--action`) which are working and used in practice are `single`, `gdb` and `noise`.

The actions `benchmark`, `trace`, `qemu-trace`, `printk` can probably be merged with the above, for instance `kafl single --trace` or `kafl single --debug --log` to run a single payload with extra debug output.

The `redqueen`, `redqueen-qemu` and `verify` actions are probably broken. If not, we may want to move them to tests/.

We should also expose the mcat.py tool. It is trivial but quite useful when something doesn't work and the output of gui/plot is not good enough.

Q: how would we run the Ghidra coverage report in this setup?

**Comment by azanegin** [comment]
Can confirm that `verify` action is indeed broken, it asks for some Redqueen machinery to run and fails.
